### ISSUE TITLE
Streak mode and syntax highlight

### ISSUE THREAD

**Issue by hutou** [justinmk/vim-sneak#195]
When g:sneak#label is set to 1, syntax highlight is cleared until cursor is moved.
Is this a feature ?
Thanks for this very useful plugin.

NB. Would it be possible to highlight search chars before **and** after the cursor position (sort of 's' + 'S' !) ?

**Comment by justinmk** [comment]
> syntax highlight is cleared until cursor is moved. Is this a feature ?

It's a feature but also a limitation. It's a feature because (1) it makes searching long lines very fast, and (2) it's usually helpful as a visual aid. But I do plan to offer an option to turn it off. 

> Would it be possible to highlight search chars before and after the cursor position (sort of 's' + 'S' !) 

"bi-directional" search is an existing request. It's neat but kind of useless. One wouldn't want it _always enabled_ (because that makes the results noisier, _all_ the time), which means you need at least 2 maps, which defeats the purpose (the main benefit of bi-directional search is being able to always use the same map). 

FWIW, you can "fake" bi-directional search by creating a custom map that uses `H` to start at the top of the window: 

    :nmap _ H<Plug>SneakLabel_s


Closing this since all of the questions are addressed in open tickets.
