### ISSUE TITLE
<BS> doesn't work across all label modes

### ISSUE THREAD

**Issue by SevereOverfl0w** [justinmk/vim-sneak#201]
It seems to work with `s` but not with the `f` and `t` shadows.

**Comment by justinmk** [comment]
What do you have f/t mapped to? I.e. which sneak `<Plug>` maps.

The `<BS>` feature is for label-mode. To change directions for non-label mode, just use `,` or whatever is mapped to `<Plug>Sneak_,` .

Note that you can create a condition mapping so that `<BS>` works when sneak is active. See `:help sneak#is_sneaking()`.

    nmap <expr> <Tab> sneak#is_sneaking() ? '<Plug>Sneak_,' : '<BS>'

**Comment by SevereOverfl0w** [comment]
```
map f <Plug>Sneak_f
map F <Plug>Sneak_F
map t <Plug>Sneak_t
map T <Plug>Sneak_T
```

I'm using these `<Plug>` maps. Also with `let g:sneak#label = 1` which I thought enabled label mode, I realise now it's just hlsearch, not label mode (doh!)

> These mappings do not invoke label-mode

from the README.

I will try your mapping, or I notice in `:help sneak#wrap()` there is examples for triggering `f` in label mode.

Sorry for my confusion.
