### ISSUE TITLE
sneak-clever-s not working

### ISSUE THREAD

**Issue by jtrees** [justinmk/vim-sneak#262]
I have the following line in my config but "clever s" still isn't working for some reason:

```
let g:sneak#s_next = 1
```

Any ideas?

[Neovim v0.4.3]

**Comment by justinmk** [comment]
works for me, and is covered by the test suite. check your mappings, bisect your plugins (remove other plugins to see if that fixes the issue, this helps narrow down the cause)

**Comment by LambdaP** [comment]
Hi. I’m dropping by because I had the same issue and found that the answer to my problem was counter-intuitive (to me at least). As I understand it, `g:sneak#s_next` needs to be set before `sneak#init()` is called, because what _actually_ matters is the value of `sneak#opt.s_next` that is set in this function. A consequence is that if you set `g:sneak#s_next` in eg `./config/nvim/after/plugin/vim-sneak.vim` then `sneak` will behave like `g:sneak#s_next` was set to `0`.

This probably deserves a mention in the documentation?
