### ISSUE TITLE
can't remove sneak highlights in <esc> remap

### ISSUE THREAD

**Issue by stumash** [justinmk/vim-sneak#287]
If I map `<esc>` like so
```vim
nnoremap <esc> <esc>:call sneak#cancel()<cr>:<esc>
```
Then when I sneak around with, e.g., `sXX`, I can hit `<esc>` to stop showing the sneak highlighting.

However, I'd also like `<esc>` to clear highlights from regular searching with `/`. So, I do
```vim
nnoremap <esc> <esc>:call sneak#cancel()<cr>:noh<cr>:<esc>
" or I do it in reverse order
" nnoremap <esc> <esc>:noh<cr>:call sneak#cancel()<cr>:<esc>
```

Problems is, if I search `/XX` once and then hit `<esc>`, it clears the search highlights. But if I search `/XX` _a second time_ then hit `<esc>`, it **does not clear the search highlights**. It **does** still clear sneak highlights though.

Any idea what's going on?

**Comment by justinmk** [comment]
sneak#cancel() checks if it exists in an `<esc>` mapping, because that is how sneak normally supports its ESC behavior: https://github.com/justinmk/vim-sneak/blob/95374ad3e4b5ef902854e8f4bcfa9a7a31a91d71/plugin/sneak.vim#L64

It doesn't know that it didn't set this mapping itself. And it can't know, because Vim doesn't provide that info. 

You can workaround this by calling `sneak#cancel()` in a slightly different way:

    nnoremap <esc> <esc>:call call('s'.'neak#cancel', [])<cr>:noh<cr>:<esc>

OTOH, perhaps sneak should do the hack to avoid this confusion.
